### ISSUE TITLE
Option to allow owner of repo to get meme

### ISSUE THREAD

**Issue by jhammarstedt** [deep5050/memes-on-issues-action#4]
**Is your feature request related to a problem? Please describe.**
If I want to get memes in my own repo, it's sad that I cannot do that as its owner...

**Describe the solution you'd like**
Add an input that can be set to true if you wish to get memes as repo owner

**Describe alternatives you've considered**
Looking for other meme Actions :(

**Comment by deep5050** [comment]
hi @jhammarstedt can you please make me clear?
you want memes on issues or PRS raised by yourself?

**Comment by jhammarstedt** [comment]
Thx for getting back @deep5050. Yes that was the idea. Just saw that you had some lines in your index.js that prevents owners from doing that. 

I understand why you technically wouldn't want that option since its for people contributing, but to be more exact I am creating a Github Actions tutorial and wanted to have your action as a fun bonus. So it will technically not be me but those doing the tutorial on their own cloned repo that runs your action.

**Comment by deep5050** [comment]
oh i get it. why not .i will be working on this in the morning (it's midnight here ;) and let you know. i will add two options `allow_owner` and `allow_bot`

**Comment by jhammarstedt** [comment]
Awesome, thank you! I thought about just making the PR myself but didn't find all the locations where you specified the input. Let me know when it works! 😊

**Comment by deep5050** [comment]
@jhammarstedt check and let me know if it works. happy coding

**Comment by jhammarstedt** [comment]
Works excellent, much appreciated!
